version: '2'
services:
    hrsystem1-app:
        image: hrsystem1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hrsystem1-mysql:3306/hrsystem1?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    hrsystem1-mysql:
        extends:
            file: mysql.yml
            service: hrsystem1-mysql
